### ISSUE TITLE
Fails to detect state change automatically

### ISSUE THREAD

**Issue by frextrite** [bkonyi/FlutterGeofencing#10]
The package fails to detect `GeofenceEvent.dwell` state automatically. To manually trigger it I need to first open Google Maps app and then switching back to the Geofencing app it detects the dwell state.

And similarly, if I exit the geofence I need to manually switch to the Google Maps app and then back to trigger the `exit` state change.

Flutter debug console doesn't have any useful information.

**Comment by frextrite** [comment]
The problem arises because the GPS location never gets updated if only this plugin is used. Switching back and forth to Google Maps, resulted in the current updated location to be stored by the OS which was later accessed by the Geofence plugin and hence resulted in the triggers. The problem is solved if the location is polled continuously or via FusedApi.

**Comment by wyklif** [comment]
@frextrite how do we poll location continuously

**Comment by frextrite** [comment]
@wyklif I can't say exactly but try looking into FusedApi and/or similar stuff.
