### ISSUE TITLE
Does it work Android O+

### ISSUE THREAD

**Issue by ubheamar** [bkonyi/FlutterGeofencing#11]

**Comment by frextrite** [comment]
Yes, it does. Checked on Android P.

**Comment by ubheamar** [comment]
Cool , Problem with me is for android below O its working but i have to start checking location before registering geofence 
but for Android O & Above still its not working foreground as well as background

**Comment by ubheamar** [comment]
Any comments will be helpful

**Comment by frextrite** [comment]
What is the error that you get? Can you paste the debug console log on sites like pastebin.com and link it here?
