### ISSUE TITLE
i have a problem with compatibility kotlin version

### ISSUE THREAD

**Issue by javs2** [bkonyi/FlutterGeofencing#12]
i´ve  import the plugin in my project, but when i try compile my project throws me this:  

         *********************************************************
WARNING: This version of firebase_core will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':geofencing' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.30

How can i update the kotlin version in the plugin?

**Comment by philipgiuliani** [comment]
Having the same problem. Is there any workaround to use the plugin anyways?

**Comment by bkonyi** [comment]
It should be upgraded now. Let me know if there's still issues.
