### ISSUE TITLE
Methods marked with @UiThread must be executed on the main thread. Current thread: AsyncTask #4

### ISSUE THREAD

**Issue by ssharma055** [bkonyi/FlutterGeofencing#18]
We are getting bellow error on

>  // Callback method name is intentionally left blank.
                    mBackgroundChannel.invokeMethod("", geofenceUpdateList)

When geofence is triggered .

W/System.err(22473): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: AsyncTask #4
W/System.err(22473): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
W/System.err(22473): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:684)
W/System.err(22473): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:80)
W/System.err(22473): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:189)
W/System.err(22473): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
W/System.err(22473): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
W/System.err(22473): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
W/System.err(22473): 	at io.flutter.plugins.geofencing.GeofencingService.onHandleWork(GeofencingService.kt:152)
W/System.err(22473): 	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
W/System.err(22473): 	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
W/System.err(22473): 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
W/System.err(22473): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(22473): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err(22473): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err(22473): 	at java.lang.Thread.run(Thread.java:761)

**Comment by bkonyi** [comment]
This should be resolved as of 2019/11/01.
