### ISSUE TITLE
Protocol FlutterPluginRegistrantCallback  showing unknown type

### ISSUE THREAD

**Issue by PrashantGauravSingh** [bkonyi/FlutterGeofencing#20]
In file GeofencingPlugin.m, showing Error: unknown type name 'FlutterPluginRegistrantCallback'
    static FlutterPluginRegistrantCallback registerPlugins = nil;
What can be done to solve this issue.

**Comment by bkonyi** [comment]
It sounds like you might be on an old version of Flutter? This has been present for quite awhile: [API here](https://github.com/flutter/engine/blob/9c00c26c8fe85915d9cbeb88560678fc44fe7752/shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h#L176).
