### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'geofencing' is using version 1.2.30.

### ISSUE THREAD

**Issue by mustafal** [bkonyi/FlutterGeofencing#23]
I had the error of the kotlin version even I have the kotlin version 1.2.71.
`Error running Gradle: ProcessException: Process "/home/serpentcs/flutter_projects/geofence_example/android/gradlew" exited abnormally: FAILURE: Build failed with an exception. * What went wrong: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'geofencing' is using version 1.2.30. * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. * Get more help at https://help.gradle.org. BUILD FAILED in 0s Command: /home/serpentcs/flutter_projects/geofence_example/android/gradlew app:properties Finished with error: Please review your Gradle project setup in the android/ folder.`

I had used your project as plugin in pubspec.yaml file, So can you please suggest me how I can use it as a plugin of flutter in another project?

**Comment by bkonyi** [comment]
The Kotlin version has been upgraded in this repo now, so that should fix your issue.
