### ISSUE TITLE
App crashes on iOS Simulator on hot restart 

### ISSUE THREAD

**Issue by ghost** [bkonyi/FlutterGeofencing#24]
The details about this issue is shared in the issue from the flutter repo here: https://github.com/flutter/flutter/issues/43621

Basically the example app (and other apps using the plugin) crashes on hot restart.

We reimplemented the plugin in Swift (https://github.com/JFreakDK/FlutterGeofencing/) but the same issue occurs in this ObjectiveC version.

**Comment by bkonyi** [comment]
Looks like the hot restart was triggering the background service to attempt to re-register all plugins. This should be fixed as of [this change](https://github.com/bkonyi/FlutterGeofencing/commit/49224f58a1d7716883a57b5ce6313da63d2c4ce5#diff-bbfe3a9166255e5fd5e3d3131f004562R28).
