### ISSUE TITLE
Include this plugin in a Plugin

### ISSUE THREAD

**Issue by marcolettieri** [bkonyi/FlutterGeofencing#31]
I'm trying to import this plugin inside a mine plugin.
All "works" but i can't register  `GeofencingService.setPluginRegistrant(this);`   as needed.
how can i set the pluginregistrant in the service from dart?

**Comment by bkonyi** [comment]
Hey @lettierimarco, thanks for filing an issue.

Is this in a new Flutter application created since the release of 1.12 (released this past Wednesday) by any chance? If so, there's probably a couple of extra steps that you'll need to do.
