### ISSUE TITLE
Is there a pub package?

### ISSUE THREAD

**Issue by HerrNiklasRaab** [bkonyi/FlutterGeofencing#4]

**Comment by javs2** [comment]
you can see this : https://flutter.dev/docs/development/packages-and-plugins/using-packages

**Comment by monmonja** [comment]
for anyone looking, they changed the documentation, to include this or a fork of this (that runs with kotlin 1.3)
```
geofencing:  
    git:  
      url: https://github.com/Eimji/FlutterGeofencing
```

**Comment by bkonyi** [comment]
I haven't published to pub myself as this is more an example plugin than something that's production ready. I do believe someone has published this plugin, although I don't think it's actively updated: https://pub.dev/packages/geofencing
