### ISSUE TITLE
Getting error while click register button in example project

### ISSUE THREAD

**Issue by Akash35pasupathi** [bkonyi/FlutterGeofencing#49]
Unhandled Exception: PlatformException(com.google.android.gms.common.api.ApiException: 1000: , null, null)
E/flutter (11788): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (11788): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (11788): <asynchronous suspension>

**Comment by MahmoudEzzatAbdul-Rahman** [comment]
Any solution for this?

**Comment by bkonyi** [comment]
This is a permissions error.
