### ISSUE TITLE
[Android] Only GeofenceEvent occurring is GeofenceEvent.exit

### ISSUE THREAD

**Issue by elouiestudent** [bkonyi/FlutterGeofencing#53]
When I added this plugin to my app, the only event that appears is GeofenceEvent.exit. I ran the example app and GeofenceEvent.enter fired. I'm not sure what part of the setup I am missing. Any help will be much appreciated!

**Comment by Friday8229** [comment]
You got it working? I'm having the same issue. The enter event is never called.
