### ISSUE TITLE
Exception has ocurred when trying register on android 

### ISSUE THREAD

**Issue by raultoto** [bkonyi/FlutterGeofencing#55]
`D/EGL_emulation(12145): eglMakeCurrent: 0xe6be2280: ver 2 0 (tinfo 0xe7db52a0)
D/eglCodecCommon(12145): setVertexArrayObject: set vao to 0 (0) 1 0
I/flutter (12145): Initializing...
D/GeofencingPlugin(12145): Initializing GeofencingService
I/flutter (12145): Initialization done
E/GeofencingPlugin(12145): Failed to add geofence: com.google.android.gms.common.api.ApiException: 1000:`

**Comment by bkonyi** [comment]
This looks like a permissions error. Make sure you have your permissions set correctly to allow for location and background location access.
