### ISSUE TITLE
A way to keep the geofence manager alive after app termination

### ISSUE THREAD

**Issue by MahmoudEzzatAbdul-Rahman** [bkonyi/FlutterGeofencing#58]
I've tried scheduling jobs using android_alarm_manager to keep the geofence manager initialized but it doesn't quite work correctly, is there a reliable way to keep the geofence manager running after app termination?

**Comment by bkonyi** [comment]
You'll need to run things in a foreground service for long-running background work. The plugin has [promoteToForeground](https://pub.dev/documentation/geofencing/latest/geofencing/GeofencingManager/promoteToForeground.html) which achieves that, but it might be a bit restrictive as this plugin isn't meant for production use.
