### ISSUE TITLE
registerWith no longer a method in GeofencingPlugin

### ISSUE THREAD

**Issue by elouiestudent** [bkonyi/FlutterGeofencing#67]
I noticed that in a recent commit updating to Flutter Android Embedding v2 the method "registerWith" was removed. This was a breaking change for my application since I register each plugin individually. How does the plugin registration process change with the new commit?

**Comment by bkonyi** [comment]
Correct. `registerWith` is part of the old Android embedding API for Flutter plugins and has been deprecated for awhile. You'll want to follow the migration instructions [here](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects).
