### ISSUE TITLE
No visible @interface

### ISSUE THREAD

**Issue by ashihCT** [bkonyi/FlutterGeofencing#7]
I tried running the example project and it fails with 10 warnings and 1 error.

Error:
`error: no visible @interface for 'FlutterHeadlessDartRunner' declares the selector 'runWithEntrypointAndLibraryUri:libraryUri:'
      [_headlessRunner runWithEntrypointAndLibraryUri:entrypoint libraryUri:uri];`

**Comment by bkonyi** [comment]
This sounds like it was an old version of Flutter and this issue could probably be resolved by running `flutter upgrade`.
